### ISSUE TITLE
Not running on windows 10

### ISSUE THREAD

**Issue by kmhigashioka** [mschwarzmueller/reactjs-basics#4] opened 2016-12-18 11:38 UTC
Hi I am getting this error on windows 10.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\kazu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.0.5
3 info using node@v6.9.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle reactjs-basics@1.0.0~prestart: reactjs-basics@1.0.0
6 silly lifecycle reactjs-basics@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle reactjs-basics@1.0.0~start: reactjs-basics@1.0.0
8 verbose lifecycle reactjs-basics@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle reactjs-basics@1.0.0~start: PATH: C:\Users\kazu\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\kazu\Downloads\reactjs-basics-01-setup\reactjs-basics-01-setup\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Users\kazu\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\kazu\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\xampp\php;C:\Users\kazu\AppData\Local\.meteor\;C:\Users\kazu\AppData\Roaming\npm
10 verbose lifecycle reactjs-basics@1.0.0~start: CWD: C:\Users\kazu\Downloads\reactjs-basics-01-setup\reactjs-basics-01-setup
11 silly lifecycle reactjs-basics@1.0.0~start: Args: [ '/d /s /c', 'npm run build' ]
12 silly lifecycle reactjs-basics@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle reactjs-basics@1.0.0~start: Failed to exec start script
14 verbose stack Error: reactjs-basics@1.0.0 start: `npm run build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\kazu\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\kazu\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid reactjs-basics@1.0.0
16 verbose cwd C:\Users\kazu\Downloads\reactjs-basics-01-setup\reactjs-basics-01-setup
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kazu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.2
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error reactjs-basics@1.0.0 start: `npm run build`
22 error Exit status 1
23 error Failed at the reactjs-basics@1.0.0 start script 'npm run build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the reactjs-basics package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs reactjs-basics
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls reactjs-basics
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by hoainamcrr** [comment] 2017-01-17 03:45
Sorry.

Hope that you can help me. tks

E:\xampp\htdocs\hoainam\training>npm start

> training@1.0.0 start E:\xampp\htdocs\hoainam\training
> npm run build


> training@1.0.0 build E:\xampp\htdocs\hoainam\training
> webpack -d && copy src/index.html dist/index.html && webpack-dev-server --content-base src/ --inline --hot

Hash: a16b26f67f9151c90f23
Version: webpack 1.14.0
Time: 49ms
        Asset     Size  Chunks             Chunk Names
    bundle.js  1.63 kB       0  [emitted]  main
bundle.js.map  1.61 kB       0  [emitted]  main
   [0] ./src/app/index.js 21 bytes {0} [built]
The syntax of the command is incorrect.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! training@1.0.0 build: `webpack -d && copy src/index.html dist/index.html && webpack-dev-server --content-base src/ --inline --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the training@1.0.0 build script 'webpack -d && copy src/index.html dist/index.html && webpack-dev-server --content-base src/ --inline --hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the training package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -d && copy src/index.html dist/index.html && webpack-dev-server --content-base src/ --inline --hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs training
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls training
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\xampp\htdocs\hoainam\training\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! training@1.0.0 start: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the training@1.0.0 start script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the training package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs training
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls training
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\xampp\htdocs\hoainam\training\npm-debug.log

**Comment by utsavmaniyar** [comment] 2017-02-23 07:25
In Windows Use this, just changing "cp" to "copy" isn't going to solve the problem 

"scripts": {
     "start": "npm run build",
     "build": "webpack -d && xcopy \"src/index.html\" \"dist/\" /F /Y && webpack-dev-server --content-base src/ --inline",
     "build:prod": "webpack -p && xcopy \"src/index.html\" \"dist/\" /F /Y"
  },﻿


Also, install babel-core from npm.

**Comment by jitsingfow** [comment] 2017-03-10 06:34
first install bable-core: npm install babel-core

then change your package.json


{
  "name": "reactapp",
  "version": "1.0.0",
  "description": "some basic ReactJS",
  "main": "index.js",
  "scripts": {
    "start": "npm run build",
    "build": "webpack -d && copy src\\index.html dist\\index.html && webpack-dev-server --content-base src\\ --inline --hot ",
    "build:prod": "webpack -p && cp src/index.html"
  },
  "keywords": [
    "reactjs"
  ],
  "author": "Jit Singfow",
  "license": "MIT",
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },
  "devDependencies": {
    "babel-loader": "^6.4.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.23.0",
    "babel-preset-stage-2": "^6.22.0",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.4.1"
  }
}

**Comment by utsavmaniyar** [comment] 2017-03-10 16:20
Thanks

*Thanks and Regards,*
*Utsav Maniyar,*
*UI/Front-End Developer*
*utsavmaniyar@gmail.com <utsavmaniyar@gmail.com>*

*Direct: **(409) 791-0207 <409-791-0207>.*

**Comment by cmevawala** [comment] 2017-04-23 08:46
What should be done so that it will run on linux and windows machines?

**Comment by hexthedev** [comment] 2017-07-17 16:52
Took way too long to fix this on my end. Turns out windows picks and chooses when you can use \ or / and when you have to use \ when defining directory paths. 

I fixed by doing this 
"build": "webpack -d && copy src\\\\index.html dist\\\\index.html /Y && webpack-dev-server --content-base src/ --inline --hot "

\\\\ - allows \ in JS strings
/Y forces override copy

**Comment by murali290987** [comment] 2017-08-13 15:48
Hi, 
I have added the below code in my package.json file.
"scripts": {
    "start": "npm run build",
    "build": "webpack -d && copy src\index.html dist\index.html /Y && webpack-dev-server --content-base src/ --inline --hot ",
    "build:prod": "webpack -p && cp src/index.html"
  },

i m facing this issue....

npm ERR! Failed to parse json
npm ERR! Unexpected token i
npm ERR! File: C:\xampp\htdocs\react-basics\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! cwd C:\xampp\htdocs\react-basics
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! file C:\xampp\htdocs\react-basics\package.json
npm ERR! code EJSONPARSE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\xampp\htdocs\react-basics\npm-debug.log
npm ERR! not ok code 0

i m using windows 10

**Comment by hexthedev** [comment] 2017-08-13 18:10
npm ERR! Failed to parse json
npm ERR! Unexpected token i

This is for sure a syntax error in the json. Check the commas. Make sure your objects have the correct syntax. To me, your error is saying youve got a random i where it shouldnt be

**Closed as completed** 2017-08-14 00:02 UTC

**Comment by murali290987** [comment] 2017-08-14 08:26
Hi,
Thanks for ur reply ...  I m nt sure what is the error here. Below code is my package.json file

{
  "name": "react-basics",
  "version": "1.0.0",
  "description": "My Node + React App",
  "main": "index.js",
  "scripts": {
    "start": "npm run build",
    "build": "webpack -d && copy src\index.html dist\index.html /Y && webpack-dev-server --content-base src/ --inline --hot",
    "build:prod": "webpack -p && cp src/index.html"
  },
  "keywords": [
    "React",
    "JS",
    "Node",
    "JS"
  ],
  "author": "Murali",
  "license": "ISC",
  "dependencies": {
    "react": "^15.6.1",
    "react-dom": "^15.6.1"
  },
  "devDependencies": {
    "babel-loader": "^7.1.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "webpack": "^3.5.4",
    "webpack-dev-server": "^2.7.1"
  }
}
Please help me....

**Comment by hexthedev** [comment] 2017-08-14 15:10
Okay so I know what the problem is. I didn't realize that github comments take \\\\ and make it \\. 

"build": "webpack -d && copy src\\index.html dist\\index.html /Y && webpack-dev-server --content-base src/ --inline --hot",

needs to be

"build": "webpack -d && copy src\\\\index.html dist\\\\index.html /Y && webpack-dev-server --content-base src/ --inline --hot",

Explaination:
Remember that in strings \\ is a special character. it's used for stuff like "\\n" for new line. SO when you write windows paths using the \\ character, in a string you need to put '\\\\'. Basically the same way '\\n' is a special character meaning new line, '\\\\' is a special character meaning \\

I updated the original comment to reflect this.

**Comment by satyadk** [comment] 2018-05-21 08:30
@superjamesmccafferty  Thanks.

It helped. 

> I fixed by doing this
> "build": "webpack -d && copy src\\index.html dist\\index.html /Y && webpack-dev-server --content-base src/ --inline --hot "
